// <auto-generated />
using System;
using FriendsNetwork.SqlRepository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FriendsNetwork.PosgreSqlRepository.Migrations
{
    [DbContext(typeof(FriendsNetworkDbContext))]
    [Migration("20250519113856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("boolean");

                    b.Property<long>("receiver_id")
                        .HasColumnType("bigint");

                    b.Property<long>("sender_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("receiver_id");

                    b.HasIndex("sender_id", "receiver_id")
                        .IsUnique();

                    b.ToTable("FriendRequests", t =>
                        {
                            t.HasCheckConstraint("CK_Request_NoSelfRequest", "sender_id <> receiver_id");
                        });
                });

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.Friendship", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("friend_id")
                        .HasColumnType("bigint");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("friend_id");

                    b.HasIndex("user_id", "friend_id")
                        .IsUnique();

                    b.ToTable("Friendships", t =>
                        {
                            t.HasCheckConstraint("CK_Friendship_NoSelfFriend", "user_id <> friend_id");
                        });
                });

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("hashed_password")
                        .HasColumnType("text");

                    b.Property<Guid?>("online_id")
                        .HasColumnType("uuid");

                    b.Property<string>("salt")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("FriendsNetwork.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FriendsNetwork.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("FriendsNetwork.Domain.Entities.User", "Friend")
                        .WithMany("FriendsOf")
                        .HasForeignKey("friend_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsNetwork.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendsNetwork.Domain.Entities.User", b =>
                {
                    b.Navigation("FriendsOf");
                });
#pragma warning restore 612, 618
        }
    }
}
